/**
 * An EF Core model snapshot → the declared schema.
 *
 * `Migrations/<Context>ModelSnapshot.cs` is C# generated by EF Core, and it is
 * the one file in a .NET repository that states the whole schema in one place:
 * every entity, every property with the *database* type EF chose, every key,
 * every index and every relationship. Read as text, never compiled (ADR-0005).
 *
 * Its shape is the reason it reads cleanly. The file is two passes of its own:
 * `modelBuilder.Entity("Ns.Order", b => { … })` first declares properties,
 * keys, indexes and `b.ToTable("orders")`, and then a *second* block for the
 * same entity declares `b.HasOne(…).WithMany(…).HasForeignKey("CustomerId")`.
 * So this reader collects entities first and resolves relationships after,
 * exactly as EF Core writes them.
 *
 * `HasColumnType("integer")` is already the database's own spelling, which is
 * what ADR-0002 asks for, so those types are taken verbatim.
 */

import type { Column, DeclaredSchema, ForeignKey, Table } from '@ledgerline/model';

export interface EfCoreSchema {
  readonly schema: DeclaredSchema;
  readonly unread: readonly { readonly reason: string; readonly line: number; readonly text: string }[];
}

/** Entity names are namespaced; the table's default name is the last segment. */
function bare(entity: string): string {
  return entity.split('.').pop() ?? entity;
}

/** The CLR types EF maps when a snapshot omits `HasColumnType` — rare, but it happens for owned types. */
const CLR: Readonly<Record<string, string>> = {
  int: 'integer',
  long: 'bigint',
  short: 'smallint',
  byte: 'smallint',
  bool: 'boolean',
  string: 'text',
  decimal: 'numeric',
  double: 'double precision',
  float: 'real',
  DateTime: 'timestamp without time zone',
  DateTimeOffset: 'timestamp with time zone',
  DateOnly: 'date',
  TimeOnly: 'time without time zone',
  Guid: 'uuid',
  TimeSpan: 'interval',
};

interface Entity {
  readonly name: string;
  table: string | null;
  schema: string;
  readonly columns: Column[];
  primaryKey: string[];
  readonly uniques: string[][];
  /** Property name → column name, because `HasColumnName` renames and keys are stated by property. */
  readonly columnOf: Map<string, string>;
}

interface Relation {
  readonly from: string;
  readonly to: string;
  readonly properties: readonly string[];
  readonly principal: readonly string[] | null;
  readonly line: number;
  readonly text: string;
}

function quoted(line: string): string[] {
  return [...line.matchAll(/"([^"]*)"/g)].map((m) => m[1]!);
}

export function parseEfCoreSnapshot(source: string): EfCoreSchema {
  const lines = source.split('\n');
  const entities = new Map<string, Entity>();
  const relations: Relation[] = [];
  const unread: { reason: string; line: number; text: string }[] = [];

  let current: Entity | null = null;
  /** The property the following fluent lines are still describing. */
  let property: { name: string; type: string | null; nullable: boolean; column: string | null } | null = null;
  /** Set while reading a `b.HasOne(...)` chain, which spans several lines. */
  let relation: { to: string; properties: string[]; principal: string[] | null; line: number; text: string } | null = null;
  /** `.IsUnique()` follows `b.HasIndex(...)` on its own line as often as it shares one. */
  let pendingIndex: { entity: Entity; columns: string[]; unique: boolean } | null = null;

  const closeProperty = (): void => {
    if (current === null || property === null) return;
    const type = property.type ?? 'text';
    const name = property.column ?? property.name;
    current.columns.push({ name, type, nullable: property.nullable });
    current.columnOf.set(property.name, name);
    property = null;
  };
  const closeRelation = (): void => {
    if (current === null || relation === null) return;
    if (relation.properties.length === 0) unread.push({ reason: `a relationship from ${bare(current.name)} with no HasForeignKey`, line: relation.line, text: relation.text });
    else relations.push({ from: current.name, to: relation.to, properties: relation.properties, principal: relation.principal, line: relation.line, text: relation.text });
    relation = null;
  };

  let n = 0;
  for (const raw of lines) {
    n++;
    const line = raw.trim();
    if (line.length === 0 || line.startsWith('//')) continue;

    const entity = /^modelBuilder\.Entity\(\s*"([^"]+)"/.exec(line);
    if (entity) {
      closeProperty();
      closeRelation();
      const name = entity[1]!;
      // Second and later blocks for the same entity add relationships to it.
      current = entities.get(name) ?? { name, table: null, schema: 'public', columns: [], primaryKey: [], uniques: [], columnOf: new Map() };
      entities.set(name, current);
      continue;
    }
    if (current === null) continue;

    const prop = /^b\.Property<([\w?.<>]+)>\(\s*"([^"]+)"\s*\)/.exec(line);
    if (prop) {
      closeProperty();
      closeRelation();
      const clr = prop[1]!.replace(/\?$/, '').split('.').pop()!;
      property = { name: prop[2]!, type: CLR[clr] ?? null, nullable: prop[1]!.endsWith('?'), column: null };
      continue;
    }

    if (property !== null) {
      const columnType = /^\.HasColumnType\(\s*"([^"]+)"\s*\)/.exec(line);
      if (columnType) {
        property = { ...property, type: columnType[1]! };
        continue;
      }
      const columnName = /^\.HasColumnName\(\s*"([^"]+)"\s*\)/.exec(line);
      if (columnName) {
        property = { ...property, column: columnName[1]! };
        continue;
      }
      const max = /^\.HasMaxLength\(\s*(\d+)\s*\)/.exec(line);
      if (max && property.type === null) {
        property = { ...property, type: `character varying(${max[1]})` };
        continue;
      }
      if (/^\.IsRequired\(\s*\)/.test(line)) {
        property = { ...property, nullable: false };
        continue;
      }
      if (line.startsWith('.')) continue;
    }

    const key = /^b\.HasKey\(([^)]*)\)/.exec(line);
    if (key) {
      closeProperty();
      current.primaryKey = quoted(key[1]!);
      continue;
    }
    const index = /^b\.HasIndex\(([^)]*)\)/.exec(line);
    if (index) {
      closeProperty();
      closeRelation();
      // `.IsUnique()` may be on this line or the next; both spellings occur.
      const columns = quoted(index[1]!);
      if (/\.IsUnique\(\s*\)/.test(line)) current.uniques.push(columns);
      else property = null;
      // Remember it in case the next line is `.IsUnique()`.
      pendingIndex = { entity: current, columns, unique: /\.IsUnique\(\s*\)/.test(line) };
      continue;
    }
    if (pendingIndex !== null && /^\.IsUnique\(\s*\)/.test(line)) {
      if (!pendingIndex.unique) pendingIndex.entity.uniques.push(pendingIndex.columns);
      pendingIndex = null;
      continue;
    }

    const toTable = /^b\.ToTable\(\s*"([^"]+)"(?:\s*,\s*"([^"]+)")?/.exec(line);
    if (toTable) {
      closeProperty();
      closeRelation();
      current.table = toTable[1]!;
      if (toTable[2] !== undefined) current.schema = toTable[2];
      continue;
    }

    const hasOne = /^b\.HasOne\(\s*"([^"]+)"/.exec(line);
    if (hasOne) {
      closeProperty();
      closeRelation();
      relation = { to: hasOne[1]!, properties: [], principal: null, line: n, text: line.slice(0, 120) };
      continue;
    }
    if (relation !== null) {
      const fk = /^\.HasForeignKey\(([^)]*)\)/.exec(line);
      if (fk) {
        relation.properties = quoted(fk[1]!);
        continue;
      }
      const principal = /^\.HasPrincipalKey\(([^)]*)\)/.exec(line);
      if (principal) {
        relation.principal = quoted(principal[1]!);
        continue;
      }
      if (line.startsWith('.')) continue;
      closeRelation();
    }

    if (/^b\.(OwnsOne|OwnsMany|HasDiscriminator|ComplexProperty)\b/.test(line)) {
      closeProperty();
      unread.push({ reason: `${/^b\.(\w+)/.exec(line)![1]} — a shape this reader does not flatten into tables`, line: n, text: line.slice(0, 120) });
      continue;
    }
    if (/^\}\);?$/.test(line)) {
      closeProperty();
      closeRelation();
    }
  }
  closeProperty();
  closeRelation();

  const tableOf = (name: string): { schema: string; table: string } | null => {
    const e = entities.get(name);
    if (e === undefined) return null;
    return { schema: e.schema, table: e.table ?? bare(e.name) };
  };

  const tables: Table[] = [];
  for (const e of entities.values()) {
    const name = e.table ?? bare(e.name);
    tables.push({
      schema: e.schema,
      name,
      columns: e.columns,
      primaryKey: e.primaryKey.map((p) => e.columnOf.get(p) ?? p),
      uniques: e.uniques.map((u) => u.map((p) => e.columnOf.get(p) ?? p)),
    });
  }

  const foreignKeys: ForeignKey[] = [];
  for (const r of relations) {
    const from = tableOf(r.from);
    const to = tableOf(r.to);
    const fromEntity = entities.get(r.from);
    const toEntity = entities.get(r.to);
    if (from === null || to === null || fromEntity === undefined || toEntity === undefined) {
      unread.push({ reason: `a relationship to ${bare(r.to)}, which this snapshot does not declare`, line: r.line, text: r.text });
      continue;
    }
    const targets = r.principal ?? toEntity.primaryKey;
    if (targets.length !== r.properties.length) {
      unread.push({ reason: `a relationship whose ${r.properties.length} columns do not match ${bare(r.to)}'s ${targets.length}`, line: r.line, text: r.text });
      continue;
    }
    foreignKeys.push({
      name: `FK_${from.table}_${to.table}_${r.properties.join('_')}`,
      from: r.properties.map((p) => ({ schema: from.schema, name: from.table, column: fromEntity.columnOf.get(p) ?? p })),
      to: targets.map((p) => ({ schema: to.schema, name: to.table, column: toEntity.columnOf.get(p) ?? p })),
    });
  }

  return {
    schema: {
      tables: tables.sort((a, b) => (`${a.schema}.${a.name}` < `${b.schema}.${b.name}` ? -1 : 1)),
      foreignKeys: foreignKeys.sort((a, b) => (a.name < b.name ? -1 : 1)),
    },
    unread,
  };
}
