/**
 * Rails' `db/schema.rb` → the declared schema.
 *
 * `schema.rb` is generated by Rails from the database itself, so it is a
 * faithful statement of what is there — and for a Rails team it is checked in,
 * which means Ledgerline can read the schema of a repository that has no
 * migrations directory it recognises.
 *
 * Read line by line, not by running Ruby: a `schema.rb` that has to be
 * evaluated to be understood is a `schema.rb` that can run anything, and
 * nothing leaves this machine, including control.
 *
 * Two places it declines to guess, both reported rather than invented:
 *
 * 1. `add_foreign_key "orders", "users"` names no column; Rails derives
 *    `user_id` by singularising the table name. The inflector here knows the
 *    regular rules and a handful of irregulars. A plural it cannot turn back
 *    into a column the table actually has is *reported*, not guessed — an
 *    invented edge is worse than a missing one.
 * 2. Anything in the file that is not `create_table`, a column, an index or a
 *    foreign key — `execute`, `enable_extension`, a view — is counted.
 */

import type { Column, DeclaredSchema, ForeignKey, Table } from '@ledgerline/model';

/** Rails' column methods, spelled as PostgreSQL reports the type (ADR-0002). */
const TYPES: Readonly<Record<string, string>> = {
  string: 'character varying',
  text: 'text',
  integer: 'integer',
  bigint: 'bigint',
  float: 'double precision',
  decimal: 'numeric',
  numeric: 'numeric',
  datetime: 'timestamp without time zone',
  timestamp: 'timestamp without time zone',
  timestamptz: 'timestamp with time zone',
  time: 'time without time zone',
  date: 'date',
  binary: 'bytea',
  boolean: 'boolean',
  uuid: 'uuid',
  json: 'json',
  jsonb: 'jsonb',
  inet: 'inet',
  cidr: 'cidr',
  macaddr: 'macaddr',
  interval: 'interval',
  money: 'money',
  serial: 'integer',
  bigserial: 'bigint',
};

const IRREGULAR: Readonly<Record<string, string>> = {
  people: 'person',
  children: 'child',
  men: 'man',
  women: 'woman',
  feet: 'foot',
  teeth: 'tooth',
  geese: 'goose',
  mice: 'mouse',
  indices: 'index',
  matrices: 'matrix',
  vertices: 'vertex',
  analyses: 'analysis',
  diagnoses: 'diagnosis',
  statuses: 'status',
  addresses: 'address',
};

/** Enough of Rails' inflector for a table name; anything else is reported, not guessed. */
export function singularize(plural: string): string {
  const lower = plural.toLowerCase();
  const irregular = IRREGULAR[lower];
  if (irregular !== undefined) return irregular;
  if (/(ss|us|is)$/.test(lower)) return lower;
  if (/ies$/.test(lower)) return `${lower.slice(0, -3)}y`;
  if (/(ch|sh|x|z|s)es$/.test(lower)) return lower.slice(0, -2);
  if (/ves$/.test(lower)) return `${lower.slice(0, -3)}f`;
  if (/s$/.test(lower)) return lower.slice(0, -1);
  return lower;
}

/** `["a", "b"]` → `['a', 'b']`. */
function columnList(list: string): string[] {
  return [...list.matchAll(/["']([^"']+)["']/g)].map((m) => m[1]!);
}

export interface RailsSchema {
  readonly schema: DeclaredSchema;
  /** Lines the reader had no rule for, so a person can see what it did not read. */
  readonly unread: readonly { readonly reason: string; readonly line: number; readonly text: string }[];
}

export function parseRailsSchema(source: string): RailsSchema {
  const tables: Table[] = [];
  const foreignKeys: ForeignKey[] = [];
  const unread: { reason: string; line: number; text: string }[] = [];
  const lines = source.split('\n');

  let current: { name: string; columns: Column[]; primaryKey: string[]; uniques: string[][] } | null = null;
  let n = 0;
  for (const raw of lines) {
    n++;
    const line = raw.trim();
    if (line.length === 0 || line.startsWith('#')) continue;

    const create = /^create_table\s+["']([^"']+)["'](.*)\s+do\s+\|(\w+)\|/.exec(line);
    if (create) {
      const [, name, options] = create as unknown as [string, string, string, string];
      const idFalse = /\bid:\s*false\b/.test(options);
      const named = /\bprimary_key:\s*["']([^"']+)["']/.exec(options);
      const idType = /\bid:\s*:(\w+)/.exec(options);
      const pk = named?.[1] ?? (idFalse ? null : 'id');
      current = {
        name,
        columns: pk === null ? [] : [{ name: pk, type: TYPES[idType?.[1] ?? 'bigserial'] ?? 'bigint', nullable: false }],
        primaryKey: pk === null ? [] : [pk],
        uniques: [],
      };
      continue;
    }

    if (current !== null) {
      if (line === 'end') {
        tables.push({ schema: 'public', name: current.name, columns: current.columns, primaryKey: current.primaryKey, uniques: current.uniques });
        current = null;
        continue;
      }
      // `t.index ["email"], name: "…", unique: true`
      const index = /^\w+\.index\s+\[([^\]]*)\](.*)$/.exec(line);
      if (index) {
        if (/\bunique:\s*true\b/.test(index[2]!)) current.uniques.push(columnList(index[1]!));
        continue;
      }
      // `t.references :user` and `t.belongs_to :user` make `user_id`.
      const reference = /^\w+\.(references|belongs_to)\s+[:"']([\w]+)["']?(.*)$/.exec(line);
      if (reference) {
        const [, , name, options] = reference as unknown as [string, string, string, string];
        const type = /\btype:\s*:(\w+)/.exec(options)?.[1] ?? 'bigint';
        current.columns.push({ name: `${name}_id`, type: TYPES[type] ?? type, nullable: !/\bnull:\s*false\b/.test(options) });
        if (/\bindex:\s*\{\s*unique:\s*true/.test(options)) current.uniques.push([`${name}_id`]);
        continue;
      }
      // `t.timestamps` is `created_at` and `updated_at`, both NOT NULL.
      if (/^\w+\.timestamps\b/.test(line)) {
        current.columns.push({ name: 'created_at', type: 'timestamp without time zone', nullable: false }, { name: 'updated_at', type: 'timestamp without time zone', nullable: false });
        continue;
      }
      const column = /^\w+\.(\w+)\s+["']([^"']+)["'](.*)$/.exec(line);
      if (column) {
        const [, method, name, options] = column as unknown as [string, string, string, string];
        const base = TYPES[method];
        if (base === undefined) {
          unread.push({ reason: `a column method this reader has no type for: ${method}`, line: n, text: line.slice(0, 120) });
          continue;
        }
        const array = /\barray:\s*true\b/.test(options);
        const limit = /\blimit:\s*(\d+)/.exec(options)?.[1];
        const precision = /\bprecision:\s*(\d+)/.exec(options)?.[1];
        const scale = /\bscale:\s*(\d+)/.exec(options)?.[1];
        let type = base;
        if (base === 'character varying' && limit !== undefined) type = `character varying(${limit})`;
        if (base === 'numeric' && precision !== undefined) type = `numeric(${precision},${scale ?? '0'})`;
        if (array) type = `${type}[]`;
        current.columns.push({ name, type, nullable: !/\bnull:\s*false\b/.test(options) });
        continue;
      }
      if (line.startsWith('t.') || line.startsWith('end')) continue;
      unread.push({ reason: 'a line inside create_table this reader has no rule for', line: n, text: line.slice(0, 120) });
      continue;
    }

    const fk = /^add_foreign_key\s+["']([^"']+)["']\s*,\s*["']([^"']+)["'](.*)$/.exec(line);
    if (fk) {
      const [, from, to, options] = fk as unknown as [string, string, string, string];
      const named = /\bcolumn:\s*["']([^"']+)["']/.exec(options)?.[1];
      const target = /\bprimary_key:\s*["']([^"']+)["']/.exec(options)?.[1] ?? 'id';
      const column = named ?? `${singularize(to)}_id`;
      const owner = tables.find((t) => t.name === from);
      if (named === undefined && owner !== undefined && !owner.columns.some((c) => c.name === column)) {
        // Rails derived a name this reader cannot reproduce. Say so; do not invent an edge.
        unread.push({ reason: `a foreign key whose column Rails derives from "${to}" and this reader cannot: no ${from}.${column}`, line: n, text: line.slice(0, 120) });
        continue;
      }
      foreignKeys.push({
        name: /\bname:\s*["']([^"']+)["']/.exec(options)?.[1] ?? `fk_rails_${from}_${column}`,
        from: [{ schema: 'public', name: from, column }],
        to: [{ schema: 'public', name: to, column: target }],
      });
      continue;
    }
    if (/^(ActiveRecord|end|enable_extension|create_schema|#)/.test(line) || /^\)?\s*do\b/.test(line)) continue;
    unread.push({ reason: 'a statement this reader has no rule for', line: n, text: line.slice(0, 120) });
  }

  return {
    schema: {
      tables: tables.sort((a, b) => (a.name < b.name ? -1 : 1)),
      foreignKeys: foreignKeys.sort((a, b) => (a.name < b.name ? -1 : 1)),
    },
    unread,
  };
}

/** The fixed places Rails puts it. */
export const RAILS_SCHEMA_FILES = ['db/schema.rb', 'db/primary_schema.rb'];
